/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>

#define PLUGIN "Amx_Rules"
#define VERSION "1.0"
#define AUTHOR "Martin"


public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	register_clcmd("say /rules", "admin_rules", 0)


}	
public admin_rules(id,level,cid) {

	if (!cmd_access(id,level,cid,1))
	return PLUGIN_CONTINUE
	
	show_motd(id,"rules.txt","Rules of the server.")
	return PLUGIN_CONTINUE
}
